spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/playstro_user_management_db
    username: root
    password: 12345678

server:
  port: 8091

logging:
  level:
    io.r2dbc.spi: INFO
    io.r2dbc.mysql: INFO