spring:
  application:
    name: playstro-search-service
  profiles:
    include: common
  webflux:
    base-path: /api/search
  data: 
    elasticsearch:
      repositories:
        enabled: true 
  elasticsearch:
    evolution:
      enabled: true
      baseline-version: 1.0
      default-content-type: application/json;charset=UTF-8
      esMigrationSuffixes: [.es]
      locations:
      - classpath:es/migration
  cloud:
    config:
      allow-override: true
      override-none: true


google:
  places:
    api:
      key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      nearbySearchUrl: https://places.googleapis.com/v1/places:searchNearby
      textSearchUrl: https://places.googleapis.com/v1/places:searchText
      fields: name, id, primaryType, types, formattedAddress, shortFormattedAddress, displayName, primaryTypeDisplayName, location, businessStatus, rating, userRatingCount


